dist: trusty
sudo: false

matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd Bridge/python
      script:
        - python echo.py

    - language: java
      jdk: oraclejdk8
      before_script:
        - echo 'start of java'
      script:
        - ./gradleTests.sh

    - language: objective-c
      osx_image: xcode9.3
      before_script:
        - echo "Currently separate Xcode project for each design"
      script:
        - cd Bridge/swift/Bridge
        - xcodebuild clean build -project Bridge.xcodeproj -scheme Bridge CODE_SIGNING_REQUIRED=NO
          -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
        - xcodebuild test -project Bridge.xcodeproj -scheme Bridge 
          -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' CODE_SIGNING_REQUIRED=NO  -enableCodeCoverage YES

        - cd ../../../Visitor/swift/Visitor
        - xcodebuild clean build -project Bridge.xcodeproj -scheme Bridge CODE_SIGNING_REQUIRED=NO
          -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
        - xcodebuild test -project Bridge.xcodeproj -scheme Bridge 
          -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' CODE_SIGNING_REQUIRED=NO  -enableCodeCoverage YES 

    - language: node_js
      node_js:
      - '9'
      addons:
        chrome: stable
        apt:
          sources:
          - google-chrome
          packages:
          - google-chrome-stable
      before_script:
        - cd Bridge/angular/bridge/
        - npm install -g codecov
        - npm install coveralls
        - yarn
        - ng lint
      script:
        - export CHROME_BIN=chromium-browser
        - xvfb-run -a npm run test -- --browsers=ChromeNoSandbox --code-coverage --watch=false
        - xvfb-run -a npm run e2e --

