dist: trusty
sudo: false

matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - cd Bridge/python
      script:
        - python echo.py

    - language: java
      jdk: oraclejdk9
      
      before_script:
        - cd Bridge/java/Bridge/
      script:
        - ./gradle test



