dist: trusty
sudo: false
matrix:
  include:
  - language: csharp
    mono: none
    dotnet: 2.1
    before_script:
    - cd TestTemplate/cSharp/ConsoleWithTest/
    script:
    - dotnet test xUnitTestStuff  
  - language: python
    python: 3.6
    before_script:
    - cd Bridge/python
    script:
    - python echo.py
  - language: java
    jdk: oraclejdk8
    before_script:
    - echo 'start of java'
    script:
    - "./gradleTests.sh"
  - language: objective-c
    osx_image: xcode9.3
    before_script:
    - echo "Currently separate Xcode project for each design"
    script:
    - cd Bridge/swift/Bridge
    - xcodebuild clean build -project Bridge.xcodeproj -scheme Bridge CODE_SIGNING_REQUIRED=NO
      -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
    - xcodebuild test -project Bridge.xcodeproj -scheme Bridge -destination 'platform=iOS
      Simulator,name=iPhone X,OS=11.3' CODE_SIGNING_REQUIRED=NO  -enableCodeCoverage
      YES
    - cd ../../../Visitor/swift/Visitor
    - xcodebuild clean build -project Visitor.xcodeproj -scheme Visitor CODE_SIGNING_REQUIRED=NO
      -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
    - xcodebuild test -project Visitor.xcodeproj -scheme Visitor -destination 'platform=iOS
      Simulator,name=iPhone X,OS=11.3' CODE_SIGNING_REQUIRED=NO  -enableCodeCoverage
      YES
  - language: node_js
    node_js:
    - '9'
    addons:
      chrome: stable
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
    before_script:
    - cd Bridge/angular/bridge/
    - npm install -g codecov
    - npm install coveralls
    - yarn
    - ng lint
    script:
    - export CHROME_BIN=chromium-browser
    - xvfb-run -a npm run test -- --browsers=ChromeNoSandbox --code-coverage --watch=false
    - xvfb-run -a npm run e2e --
  - language: go
    go:
    - 1.10.1
    env:
    - GOMAXPROCS=4
    os:
    - linux
    install:
    - go get github.com/stretchr/testify/assert
    before_install:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script:
    - export GOPATH=`pwd`/Bridge/go/Bridge
    - go test -race -v -coverprofile=c1.out bridge
    after_success:
    - cat c0.out > c.out
    - bash <(curl -s https://codecov.io/bash)
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in ./encrypt/septa.json.enc -out ./encrypt/septa.json -d
- mkdir -p $HOME/.google_java_firebase
- cp ./encrypt/septa.json $HOME/.google_java_firebase



